FROM node:16-alpine

WORKDIR /app

# Copy package files
COPY frontend/package.json frontend/package-lock.json /app/frontend/

# Install Node.js dependencies
WORKDIR /app/frontend
RUN npm install
RUN npm install bootstrap-icons

# Copy the rest of the frontend code
COPY frontend/ /app/frontend/

# Set working directory to the frontend directory
WORKDIR /app/frontend

# Start the development server
CMD ["npm", "start"]